update port log and health status
eclipse-xpanse/policy-man pull request #2
Opened 2023-09-22 07:57 UTC by baixinsui

2023-09-22 08:14 UTC, iskey commented on log/log.go
> +			TimestampFormat: time.DateTime,
```suggestion
			TimestampFormat: "2006/01/02 - 15:04:05",
```

2023-09-22 08:14 UTC, iskey commented on log/log.go
> +			TimestampFormat: time.DateTime,
```suggestion
			TimestampFormat: "2006/01/02 - 15:04:05",
```

2023-09-22 08:15 UTC, iskey requested changes
comments added.
The TimestampFormat should be a fixed timestamp.
https://stackoverflow.com/questions/42217308/go-time-format-how-to-understand-meaning-of-2006-01-02-layout

2023-09-22 09:25 UTC, iskey requested changes
some minor comments added.

2023-09-22 09:25 UTC, iskey commented on server/health_status.go
> +const OK = "OK"
You don't need to use variables here, `string` is ok.
or a new Enum would be better if you insist.

2023-09-22 09:25 UTC, iskey commented on server/health_status.go
> +package server
License should be added here.

2023-09-24 17:46 UTC, swaroopar requested changes

2023-09-24 17:46 UTC, swaroopar commented on config/conf.go
> +port: "9091" # ignore this port number if auto_tls is enabled (listen 443).
in case of auto_tls, we can use there 9443 instead of the default port.

2023-09-24 17:46 UTC, swaroopar commented on server/health_status.go
> +type HealthStatus struct {
would it make sense to move all types to a different directory?

2023-09-24 17:46 UTC, swaroopar commented on server/health_status.go
> +	HealthStatus string `json:"healthStatus" binding:"required"`
yes enum is better here.

2023-09-25 04:02 UTC, swaroopar requested changes

2023-09-25 04:02 UTC, swaroopar commented on server/handle_policy_eval.go
>  	return
do we need this explicit `return`?

2023-09-25 04:02 UTC, swaroopar commented on .gitignore
> +policy-man.iml
its better to ignore all *.iml files.

2023-09-25 09:17 UTC, iskey approved these changes
LGTM

2023-09-25 09:52 UTC, swaroopar approved these changes
LGTM

2023-09-25 09:52 UTC, merged